name: Build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests
        run: ./gradlew test

  regenerate-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@8dc19fbd6451fa106a68ecb2dafeeeb90dff3a29 # latest

      - name: Update deps.json file
        run: $(nix build .#kotlin-lsp.mitmCache.updateScript --print-out-paths --no-link)

      - name: Commit deps.json file
        run: |
          if [ ! -n "$(git status --porcelain)" ]; then
            exit
          fi
          git add -A
          git config user.name "github-actions"
          git config user.email "action@github.com"
          git commit -m "build(nix): update deps.json [skip ci]"
          git push
